# Generated by Django 4.2.4 on 2023-09-29 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banks',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='branches',
            fields=[
                ('ifsc', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.banks')),
            ],
        ),
    ]
